// src/components/chrome/Breadcrumb.svelte
<script lang="ts">
  import {
    ChevronRight,
    Code2,
    Eye,
    FileDown,
    FolderOpen,
    Maximize2,
    Monitor,
    PanelLeftClose,
    PanelLeftOpen,
    PanelTopClose,
    PanelTopOpen,
    Pilcrow,
    Settings,
  } from "@/lib/icons";
  import { Button, Icon } from "@/components/primitives";
  import { language, getT } from "@/lib/i18n";
  import { shortcutLabel } from "@/lib";
  import type { WritingDisplay, WritingFontSize, WritingLineHeight } from "@/lib";
  import ThemeButton from "./ThemeButton.svelte";
  import exciteUrl from "@/assets/mascot/excite.png";

  let {
    sidebarOpen,
    onToggleSidebar,
    rootPath,
    activePath,
    saveStatus,
    onExportPdf,
    onOpenProject,
    titlebarVisible,
    onToggleTitlebar,
    vimOn,
    onToggleVim,
    writingDisplay,
    onWritingFontSizeChange,
    onWritingLineHeightChange,
    onResetWritingDisplay,
    editorMode,
    onSetEditorMode,
    onToggleFullscreen,
    onOpenSettings,
  }: {
    sidebarOpen: boolean;
    onToggleSidebar: () => void;
    rootPath: string | null;
    activePath: string | null;
    saveStatus: "idle" | "dirty" | "saving" | "saved";
    onExportPdf?: () => void;
    onOpenProject?: () => void;
    titlebarVisible: boolean;
    onToggleTitlebar: () => void;
    vimOn?: boolean;
    onToggleVim?: () => void;
    writingDisplay: WritingDisplay;
    onWritingFontSizeChange: (value: WritingFontSize) => void;
    onWritingLineHeightChange: (value: WritingLineHeight) => void;
    onResetWritingDisplay: () => void;
    editorMode?: "raw" | "prose" | "preview" | "presentation";
    onSetEditorMode?: (mode: "raw" | "prose" | "preview" | "presentation") => void;
    onToggleFullscreen?: () => void;
    onOpenSettings?: () => void;
  } = $props();

  let t = $derived(getT($language));

  const MAX_SEGMENTS = 4;

  function pathSegments(path: string): string[] {
    const parts = path.split(/[\\/]/).filter(Boolean);
    if (parts.length <= MAX_SEGMENTS) return parts;
    return ["…", ...parts.slice(-MAX_SEGMENTS)];
  }

  function statusLabel(status: "idle" | "dirty" | "saving" | "saved"): string {
    switch (status) {
      case "saving": return t("breadcrumb.saving");
      case "dirty":  return t("breadcrumb.unsaved");
      case "saved":  return t("breadcrumb.saved");
      default:       return "";
    }
  }

  let path = $derived(activePath ?? rootPath);
  let segments = $derived(path ? pathSegments(path) : []);
  let label = $derived(statusLabel(saveStatus));
</script>

<div class="mdv-breadcrumb" data-tauri-drag-region>
  <Button
    data-tooltip={shortcutLabel(sidebarOpen ? t("breadcrumb.hideSidebarShortcut") : t("breadcrumb.showSidebarShortcut"))}
    aria-label={sidebarOpen ? t("breadcrumb.hideSidebar") : t("breadcrumb.showSidebar")}
    onclick={onToggleSidebar}
  >
    {#snippet icon()}
      <Icon icon={sidebarOpen ? PanelLeftClose : PanelLeftOpen} size={14} strokeWidth={1.5} />
    {/snippet}
  </Button>

  <nav class="mdv-breadcrumb__path" aria-label={t("breadcrumb.path")} data-tauri-drag-region>
    {#if segments.length === 0}
      <span class="mdv-breadcrumb__placeholder">{t("breadcrumb.noFile")}</span>
    {:else}
      {#each segments as seg, i}
        <span class="mdv-breadcrumb__seg-row">
          {#if i > 0}
            <Icon icon={ChevronRight} size={11} strokeWidth={1.5} title="separator" />
          {/if}
          <span class="mdv-breadcrumb__seg" class:is-leaf={i === segments.length - 1}>{seg}</span>
        </span>
      {/each}
    {/if}
  </nav>

  <div class="mdv-breadcrumb__status" data-status={saveStatus}>
    {#if saveStatus !== "idle"}
      {#if saveStatus === "saved"}
        <img src={exciteUrl} alt="" aria-hidden width={16} height={16} draggable={false} class="mdv-breadcrumb__excite" />
      {:else}
        <span class="mdv-breadcrumb__dot" aria-hidden />
      {/if}
      <span class="mdv-breadcrumb__status-label">{label}</span>
    {/if}
  </div>

  <div class="mdv-breadcrumb__actions" data-tauri-drag-region>

    <!-- Tools : boutons de mode (uniquement pour les fichiers .md) -->
    {#if onSetEditorMode}
      <div class="mdv-breadcrumb__mode-group">
        <Button
          data-tooltip="Présentation"
          aria-label="Mode présentation"
          aria-pressed={editorMode === "presentation"}
          onclick={() => onSetEditorMode?.("presentation")}
        >
          {#snippet icon()}
            <Icon icon={Monitor} size={14} strokeWidth={1.5} />
          {/snippet}
        </Button>
        <Button
          data-tooltip="Preview"
          aria-label="Mode preview"
          aria-pressed={editorMode === "preview"}
          onclick={() => onSetEditorMode?.("preview")}
        >
          {#snippet icon()}
            <Icon icon={Eye} size={14} strokeWidth={1.5} />
          {/snippet}
        </Button>
        <div class="mdv-breadcrumb__mode-sep" aria-hidden="true"></div>
        <Button
          data-tooltip="Prose"
          aria-label="Mode prose"
          aria-pressed={editorMode === "prose"}
          onclick={() => onSetEditorMode?.("prose")}
        >
          {#snippet icon()}
            <Icon icon={Pilcrow} size={14} strokeWidth={1.5} />
          {/snippet}
        </Button>
        <Button
          data-tooltip="Raw"
          aria-label="Mode raw"
          aria-pressed={editorMode === "raw"}
          onclick={() => onSetEditorMode?.("raw")}
        >
          {#snippet icon()}
            <Icon icon={Code2} size={14} strokeWidth={1.5} />
          {/snippet}
        </Button>
      </div>
    {/if}

    <!-- Files : export PDF + ouvrir un projet -->
    <div class="mdv-breadcrumb__file-actions">
      <Button
        data-tooltip={shortcutLabel(t("app.exportPdfShortcut"))}
        aria-label={t("app.exportPdf")}
        onclick={onExportPdf}
      >
        {#snippet icon()}
          <Icon icon={FileDown} size={13} strokeWidth={1.5} />
        {/snippet}
      </Button>
      <Button
        data-tooltip={t("app.openProjectShortcut")}
        aria-label={t("app.openProject")}
        onclick={onOpenProject}
      >
        {#snippet icon()}
          <Icon icon={FolderOpen} size={13} strokeWidth={1.5} />
        {/snippet}
      </Button>
    </div>

    <!-- Config : toujours visibles -->
    <div class="mdv-breadcrumb__config">
      <Button
        data-tooltip={titlebarVisible ? t("title.hideBreadcrumb") : t("title.showBreadcrumb")}
        aria-label={titlebarVisible ? t("title.hideBreadcrumb") : t("title.showBreadcrumb")}
        aria-pressed={!titlebarVisible}
        onclick={onToggleTitlebar}
      >
        {#snippet icon()}
          <Icon icon={titlebarVisible ? PanelTopClose : PanelTopOpen} size={14} strokeWidth={1.5} />
        {/snippet}
      </Button>
      {#if onToggleFullscreen}
        <Button
          data-tooltip="Plein écran"
          aria-label="Basculer le plein écran"
          onclick={onToggleFullscreen}
        >
          {#snippet icon()}
            <Icon icon={Maximize2} size={14} strokeWidth={1.5} />
          {/snippet}
        </Button>
      {/if}
      <ThemeButton
        {vimOn}
        {onToggleVim}
        {writingDisplay}
        {onWritingFontSizeChange}
        {onWritingLineHeightChange}
        {onResetWritingDisplay}
      />
      {#if onOpenSettings}
        <Button
          data-tooltip="Paramètres"
          aria-label="Paramètres du rendu Markdown"
          onclick={onOpenSettings}
        >
          {#snippet icon()}
            <Icon icon={Settings} size={14} strokeWidth={1.5} />
          {/snippet}
        </Button>
      {/if}
    </div>

  </div>
</div>

// src/components/chrome/breadcrumb.tsx
import {
  Check,
  ChevronRight,
  Code2,
  Copy,
  FileDown,
  FilePlus2,
  FileText,
  FolderOpen,
  PanelLeftClose,
  PanelLeftOpen,
  PanelTopClose,
  PanelTopOpen,
  Pilcrow,
} from "lucide-react";
import { Button, Icon } from "@/components/primitives";
import {
  shortcutLabel,
  startWindowDrag,
  useI18n,
  type Translate,
  type WritingDisplay,
  type WritingFontSize,
  type WritingLineHeight,
} from "@/lib";
import { ThemeButton } from "./theme-button";
import exciteUrl from "@/assets/mascot/excite.png";

export type SaveStatus = "idle" | "dirty" | "saving" | "saved";

type BreadcrumbProps = {
  sidebarOpen: boolean;
  onToggleSidebar: () => void;
  rootPath: string | null;
  activePath: string | null;
  saveStatus: SaveStatus;
  onNewFile?: () => void;
  onOpenFile?: () => void;
  onOpenFolder?: () => void;
  onCopyMarkdown?: () => void;
  onExportPdf?: () => void;
  copyPulse?: boolean;
  titlebarVisible: boolean;
  onToggleTitlebar: () => void;
  readingMode?: boolean;
  onToggleReading?: () => void;
  vimOn?: boolean;
  onToggleVim?: () => void;
  writingDisplay: WritingDisplay;
  onWritingFontSizeChange: (value: WritingFontSize) => void;
  onWritingLineHeightChange: (value: WritingLineHeight) => void;
  onResetWritingDisplay: () => void;
  prosemarkOn?: boolean;
  onToggleProsemark?: () => void;
};

const MAX_SEGMENTS = 4;

function pathSegments(path: string): string[] {
  const parts = path.split(/[\\/]/).filter(Boolean);
  if (parts.length <= MAX_SEGMENTS) return parts;
  return ["…", ...parts.slice(-MAX_SEGMENTS)];
}

function statusLabel(status: SaveStatus, t: Translate): string {
  switch (status) {
    case "saving":
      return t("breadcrumb.saving");
    case "dirty":
      return t("breadcrumb.unsaved");
    case "saved":
      return t("breadcrumb.saved");
    default:
      return "";
  }
}

export function Breadcrumb({
  sidebarOpen,
  onToggleSidebar,
  rootPath,
  activePath,
  saveStatus,
  onNewFile,
  onOpenFile,
  onOpenFolder,
  onCopyMarkdown,
  onExportPdf,
  copyPulse = false,
  titlebarVisible,
  onToggleTitlebar,
  vimOn,
  onToggleVim,
  writingDisplay,
  onWritingFontSizeChange,
  onWritingLineHeightChange,
  onResetWritingDisplay,
  prosemarkOn,
  onToggleProsemark,
}: BreadcrumbProps) {
  const { t } = useI18n();
  const path = activePath ?? rootPath;
  const segments = path ? pathSegments(path) : [];
  const label = statusLabel(saveStatus, t);

  return (
    <div className="mdv-breadcrumb" data-tauri-drag-region onMouseDown={startWindowDrag}>
      <Button
        data-tooltip={shortcutLabel(sidebarOpen ? t("breadcrumb.hideSidebarShortcut") : t("breadcrumb.showSidebarShortcut"))}
        aria-label={sidebarOpen ? t("breadcrumb.hideSidebar") : t("breadcrumb.showSidebar")}
        onClick={onToggleSidebar}
        icon={
          <Icon
            icon={sidebarOpen ? PanelLeftClose : PanelLeftOpen}
            size={14}
            strokeWidth={1.5}
          />
        }
      />

      <nav className="mdv-breadcrumb__path" aria-label={t("breadcrumb.path")} data-tauri-drag-region>
        {segments.length === 0 ? (
          <span className="mdv-breadcrumb__placeholder">{t("breadcrumb.noFile")}</span>
        ) : (
          segments.map((seg, i) => (
            <span key={`${seg}-${i}`} className="mdv-breadcrumb__seg-row">
              {i > 0 ? (
                <Icon icon={ChevronRight} size={11} strokeWidth={1.5} title="separator" />
              ) : null}
              <span className={`mdv-breadcrumb__seg${i === segments.length - 1 ? " is-leaf" : ""}`}>
                {seg}
              </span>
            </span>
          ))
        )}
      </nav>

      <div className="mdv-breadcrumb__status" data-status={saveStatus}>
        {saveStatus !== "idle" ? (
          <>
            {saveStatus === "saved" ? (
              <img
                src={exciteUrl}
                alt=""
                aria-hidden
                width={16}
                height={16}
                draggable={false}
                className="mdv-breadcrumb__excite"
              />
            ) : (
              <span className="mdv-breadcrumb__dot" aria-hidden />
            )}
            <span className="mdv-breadcrumb__status-label">{label}</span>
          </>
        ) : null}
      </div>

      <div className="mdv-breadcrumb__actions" data-tauri-drag-region>
        {/* view controls: hide titlebar, reading mode, theme */}
        <Button
          data-tooltip={titlebarVisible ? t("title.hideBreadcrumb") : t("title.showBreadcrumb")}
          aria-label={titlebarVisible ? t("title.hideBreadcrumb") : t("title.showBreadcrumb")}
          aria-pressed={!titlebarVisible}
          onClick={onToggleTitlebar}
          icon={
            <Icon
              icon={titlebarVisible ? PanelTopClose : PanelTopOpen}
              size={14}
              strokeWidth={1.5}
            />
          }
        />
        <ThemeButton
          vimOn={vimOn}
          onToggleVim={onToggleVim}
          writingDisplay={writingDisplay}
          onWritingFontSizeChange={onWritingFontSizeChange}
          onWritingLineHeightChange={onWritingLineHeightChange}
          onResetWritingDisplay={onResetWritingDisplay}
        />
        {onToggleProsemark != null ? (
          <Button
            data-tooltip={prosemarkOn ? "raw code" : "prose"}
            aria-label={prosemarkOn ? "switch to raw code" : "switch to prose mode"}
            aria-pressed={prosemarkOn}
            onClick={onToggleProsemark}
            icon={
              <Icon
                icon={prosemarkOn ? Pilcrow : Code2}
                size={14}
                strokeWidth={1.5}
              />
            }
          />
        ) : null}

        {/* file actions — border-left matches the status→actions separator */}
        <div className="mdv-breadcrumb__file-actions">
          {onCopyMarkdown ? (
            <button
              type="button"
              className={`mdv-copybtn${copyPulse ? " is-copied" : ""}`}
              data-tooltip={copyPulse ? t("app.copied") : shortcutLabel(t("app.copyMarkdownShortcut"))}
              aria-label={copyPulse ? t("app.copied") : t("app.copyMarkdown")}
              onClick={onCopyMarkdown}
            >
              <span className="mdv-copybtn__icon mdv-copybtn__icon--copy" aria-hidden>
                <Icon icon={Copy} size={12} strokeWidth={1.5} />
              </span>
              <span className="mdv-copybtn__icon mdv-copybtn__icon--check" aria-hidden>
                <Icon icon={Check} size={13} strokeWidth={2} />
              </span>
            </button>
          ) : null}
          <Button
            data-tooltip={shortcutLabel(t("app.exportPdfShortcut"))}
            aria-label={t("app.exportPdf")}
            onClick={onExportPdf}
            icon={<Icon icon={FileDown} size={13} strokeWidth={1.5} />}
          />
          <Button
            data-tooltip={shortcutLabel(t("app.newFileShortcut"))}
            aria-label={t("app.newFile")}
            onClick={onNewFile}
            icon={<Icon icon={FilePlus2} size={13} strokeWidth={1.5} />}
          />
          <Button
            data-tooltip={shortcutLabel(t("app.openFileShortcut"))}
            aria-label={t("app.openFile")}
            onClick={onOpenFile}
            icon={<Icon icon={FileText} size={13} strokeWidth={1.5} />}
          />
          <Button
            data-tooltip={shortcutLabel(t("app.openFolderShortcut"))}
            aria-label={t("app.openFolder")}
            onClick={onOpenFolder}
            icon={<Icon icon={FolderOpen} size={13} strokeWidth={1.5} />}
          />
        </div>
      </div>
    </div>
  );
}
