// src/components/overlays/drop-overlay.tsx
import { FileText } from "lucide-react";
import inspectUrl from "@/assets/mascot/inspect.png";

type DropOverlayProps = {
  active: boolean;
};

export function DropOverlay({ active }: DropOverlayProps) {
  if (!active) return null;
  return (
    <div className="mdv-drop" role="status" aria-live="polite">
      <div className="mdv-drop__panel">
        <img
          src={inspectUrl}
          alt=""
          aria-hidden
          width={120}
          height={120}
          draggable={false}
          className="mdv-drop__art"
        />
        <div className="mdv-drop__icon-row">
          <FileText size={16} strokeWidth={1.5} />
          <span>drop your markdown here</span>
        </div>
        <span className="mdv-drop__hint">.md · .markdown · .mdx</span>
      </div>
    </div>
  );
}

// src/components/overlays/DropOverlay.svelte
<script lang="ts">
import { FileText } from "lucide-svelte";
import inspectUrl from "@/assets/mascot/inspect.png";

let { active }: { active: boolean } = $props();
</script>

{#if active}
  <div class="mdv-drop" role="status" aria-live="polite">
    <div class="mdv-drop__panel">
      <img
        src={inspectUrl}
        alt=""
        aria-hidden="true"
        width={120}
        height={120}
        draggable={false}
        class="mdv-drop__art"
      />
      <div class="mdv-drop__icon-row">
        <FileText size={16} strokeWidth={1.5} />
        <span>drop your markdown here</span>
      </div>
      <span class="mdv-drop__hint">.md · .markdown · .mdx</span>
    </div>
  </div>
{/if}
