// src/components/overlays/toast.tsx
import { useEffect, useState } from "react";
import { X } from "lucide-react";
import { Button, Icon } from "@/components/primitives";
import sadUrl from "@/assets/mascot/sad.png";
import exciteUrl from "@/assets/mascot/excite.png";

export type ToastAction = {
  label: string;
  onClick: () => void | Promise<void>;
};

type ToastProps = {
  open: boolean;
  message: string;
  onDismiss: () => void;
  action?: ToastAction;
  secondAction?: ToastAction;
  variant?: "error" | "info";
  /** ms before auto-dismiss; null disables. errors default manual, infos auto-dismiss. */
  durationMs?: number | null;
};

const DEFAULT_DURATION: Record<"error" | "info", number | null> = {
  error: null, // errors stay until dismissed
  info: 3500,
};

const EXIT_MS = 220;

export function Toast({
  open,
  message,
  onDismiss,
  action,
  secondAction,
  variant = "error",
  durationMs,
}: ToastProps) {
  const [leaving, setLeaving] = useState(false);

  const effectiveDuration =
    durationMs === undefined ? DEFAULT_DURATION[variant] : durationMs;

  useEffect(() => {
    if (!open) {
      setLeaving(false);
      return;
    }
    if (effectiveDuration == null) return;
    const timer = window.setTimeout(() => {
      setLeaving(true);
      window.setTimeout(onDismiss, EXIT_MS);
    }, effectiveDuration);
    return () => window.clearTimeout(timer);
  }, [open, effectiveDuration, onDismiss]);

  if (!open) return null;
  const art = variant === "info" ? exciteUrl : sadUrl;

  const dismissWithExit = () => {
    setLeaving(true);
    window.setTimeout(onDismiss, EXIT_MS);
  };

  return (
    <div
      className={`mdv-toast mdv-toast--${variant}${leaving ? " is-leaving" : ""}`}
      role={variant === "error" ? "alert" : "status"}
    >
      <img
        src={art}
        alt=""
        aria-hidden
        width={28}
        height={28}
        draggable={false}
        className="mdv-toast__art"
      />
      <span className="mdv-toast__msg">{message}</span>
      {action ? (
        <button
          type="button"
          className="mdv-toast__action"
          onClick={() => {
            void action.onClick();
            dismissWithExit();
          }}
        >
          {action.label}
        </button>
      ) : null}
      {secondAction ? (
        <button
          type="button"
          className="mdv-toast__action"
          onClick={() => {
            void secondAction.onClick();
            dismissWithExit();
          }}
        >
          {secondAction.label}
        </button>
      ) : null}
      <Button
        className="mdv-toast__dismiss"
        title="dismiss"
        aria-label="dismiss"
        onClick={dismissWithExit}
        icon={<Icon icon={X} size={11} strokeWidth={1.5} />}
      />
    </div>
  );
}

// src/components/overlays/Toast.svelte
<script lang="ts">
import { X } from "lucide-svelte";
import { Button, Icon } from "@/components/primitives";
import sadUrl from "@/assets/mascot/sad.png";
import exciteUrl from "@/assets/mascot/excite.png";

export type ToastAction = {
  label: string;
  onClick: () => void | Promise<void>;
};

let {
  open,
  message,
  onDismiss,
  action = undefined,
  secondAction = undefined,
  variant = "error",
  durationMs = undefined,
}: {
  open: boolean;
  message: string;
  onDismiss: () => void;
  action?: ToastAction;
  secondAction?: ToastAction;
  variant?: "error" | "info";
  durationMs?: number | null;
} = $props();

const DEFAULT_DURATION: Record<"error" | "info", number | null> = {
  error: null,
  info: 3500,
};

const EXIT_MS = 220;

let leaving = $state(false);

let effectiveDuration = $derived(
  durationMs === undefined ? DEFAULT_DURATION[variant] : durationMs,
);

$effect(() => {
  if (!open) {
    leaving = false;
    return;
  }
  if (effectiveDuration == null) return;
  const timer = window.setTimeout(() => {
    leaving = true;
    window.setTimeout(onDismiss, EXIT_MS);
  }, effectiveDuration);
  return () => window.clearTimeout(timer);
});

const dismissWithExit = () => {
  leaving = true;
  window.setTimeout(onDismiss, EXIT_MS);
};

let art = $derived(variant === "info" ? exciteUrl : sadUrl);
</script>

{#snippet dismissIcon()}
  <Icon icon={X} size={11} strokeWidth={1.5} />
{/snippet}

{#if open}
  <div
    class="mdv-toast mdv-toast--{variant}{leaving ? " is-leaving" : ""}"
    role={variant === "error" ? "alert" : "status"}
  >
    <img
      src={art}
      alt=""
      aria-hidden="true"
      width={28}
      height={28}
      draggable={false}
      class="mdv-toast__art"
    />
    <span class="mdv-toast__msg">{message}</span>
    {#if action}
      <button
        type="button"
        class="mdv-toast__action"
        onclick={() => { void action.onClick(); dismissWithExit(); }}
      >
        {action.label}
      </button>
    {/if}
    {#if secondAction}
      <button
        type="button"
        class="mdv-toast__action"
        onclick={() => { void secondAction.onClick(); dismissWithExit(); }}
      >
        {secondAction.label}
      </button>
    {/if}
    <Button
      class="mdv-toast__dismiss"
      title="dismiss"
      aria-label="dismiss"
      onclick={dismissWithExit}
      icon={dismissIcon}
    />
  </div>
{/if}
