// src/components/primitives/button.tsx
import type { ButtonHTMLAttributes, ReactNode } from "react";

type ButtonProps = ButtonHTMLAttributes<HTMLButtonElement> & {
  variant?: "ghost" | "solid";
  size?: "sm" | "md";
  icon?: ReactNode;
  iconRight?: ReactNode;
};

/** Ghost (default) or solid variant. Accepts icon, iconRight, children. */
export function Button({
  variant = "ghost",
  size = "sm",
  icon,
  iconRight,
  children,
  className,
  ...rest
}: ButtonProps) {
  const classes = ["mdv-btn", `mdv-btn--${variant}`, `mdv-btn--${size}`];
  if (className) classes.push(className);
  return (
    <button {...rest} className={classes.join(" ")}>
      {icon ? <span className="mdv-btn__icon">{icon}</span> : null}
      {children ? <span className="mdv-btn__label">{children}</span> : null}
      {iconRight ? <span className="mdv-btn__icon">{iconRight}</span> : null}
    </button>
  );
}

// src/components/primitives/Button.svelte
<script lang="ts">
import type { Snippet } from "svelte";

let {
  variant = "ghost",
  size = "sm",
  icon,
  iconRight,
  children,
  class: className = "",
  ...rest
}: {
  variant?: "ghost" | "solid";
  size?: "sm" | "md";
  icon?: Snippet;
  iconRight?: Snippet;
  children?: Snippet;
  class?: string;
} = $props();

let classes = $derived(
  ["mdv-btn", `mdv-btn--${variant}`, `mdv-btn--${size}`, className]
    .filter(Boolean)
    .join(" "),
);
</script>

<button class={classes} {...rest}>
  {#if icon}
    <span class="mdv-btn__icon">{@render icon()}</span>
  {/if}
  {#if children}
    <span class="mdv-btn__label">{@render children()}</span>
  {/if}
  {#if iconRight}
    <span class="mdv-btn__icon">{@render iconRight()}</span>
  {/if}
</button>
